### ISSUE TITLE
Obtaining GVSU domain name.

### ISSUE THREAD

**Issue by WildScotsmen** [alDuncanson/marten-application#9]
We need to look into how to obtain a full-qualified domain name (FQDN) that contains "gvsu.edu" as the domain. This is to qualify our application as the work of the Grand Valley State University and to demonstrate to users that this is an actual project of the biology department.

For this issue to be complete, we need to:
* Seek out the appropriate faculty members in charge of obtaining an FQDN with the GVSU domain.
* Decide whether or not obtaining a GVSU domain name is feasible for the time we've been allotted.

**Comment by malfecient** [comment]
Meet with Lawrence about GVSU hosting the app
